### ISSUE TITLE
Projected bandstructures/DOS as subplots Error

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#102]
Hi Matthew,
            I am trying to execute Projected bandstructures/DOS as subplots with custom colours example. But i am facing following error. Please guide me how to fix this error.

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-d90b98d0ce04> in <module>
     12         "Si",
     13         axes[ind],
---> 14         dispersion_kwargs
     15     )
     16 

~/.local/lib/python3.6/site-packages/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     82         except Exception as exc:
     83             if 'TclError' not in type(exc).__name__:
---> 84                 raise exc
     85 
     86             print_failure('Caught exception: {}'.format(type(exc).__name__))

~/.local/lib/python3.6/site-packages/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     78             # now actually call the function
     79             set_style(style)
---> 80             result = function(*args, **kwargs)
     81 
     82         except Exception as exc:

~/.local/lib/python3.6/site-packages/matador/plotting/spectral_plotting.py in dispersion_plot(seeds, ax_dispersion, kwargs, bbox_extra_artists)
    341             ax_dispersion = projected_bandstructure_plot(dispersion, ax_dispersion, path,
    342                                                          bbox_extra_artists, eigs=eigs,
--> 343                                                          **kwargs)
    344             kwargs['band_colour'] = 'grey'
    345             plotted_pdis = True

~/.local/lib/python3.6/site-packages/matador/plotting/spectral_plotting.py in projected_bandstructure_plot(dispersion, ax, path, bbox_extra_artists, eigs, pdis_interpolation_factor, pdis_point_scale, projectors_to_plot, **kwargs)
    714             raise RuntimeError(
    715                 "None of the desired projectors {} could be found in {}"
--> 716                 .format(projectors_to_plot, dispersion.projectors)
    717             )
    718 

RuntimeError: None of the desired projectors [('Si', 's', None)] could be found in [('Si', None, None)]

Best Wishes
Sajid

**Comment by ml-evs** [comment]
It looks like the calculation data you are trying to plot only contains a species projector "Si" and no data on angular momentum channels, so you need to re-run with `pdos: species_ang` in OptaDOS.

**Comment by sajidurehman** [comment]
Hi Matthew,
               I used the following Si.odi.
pdos: species_ang
pdispersion: species
adaptive_smearing: 1
set_efermi_zero: True
dos_per_volume: True
broadening: adaptive
dos_spacing: 0.01

**Comment by ml-evs** [comment]
Sorry, typo in my last comment, `pdispersion: species_ang` is what you need. Your `.pdis.dat` file at the moment will just contain one projector.

**Comment by sajidurehman** [comment]
Thank you for correction. But still there are some warnings and both Si(s) and Si(p) have same colours
![image](https://user-images.githubusercontent.com/33825577/90155527-e1bf3100-dda4-11ea-9ee7-e4a9d68e6aac.png)

**Comment by ml-evs** [comment]
The warnings are pretty inconsequential there, as path labels seem to have been made anyway.

I've just noticed a tiny change needs to be made to the code in the examples, as the keyword argument is now `"colours"` not `"projector_colours"`, i.e.

```diff
for ind, proj in enumerate([[("Si", "s", None)], [("Si", "p", None)]]):
    dispersion_kwargs = {
        "projectors_to_plot": proj, 
        "plot_pdis": True, 
        "pdis_interpolation_factor": 10,
+       "colours": [colours_override[ind]]
-       "projector_colours": [colours_override[ind]]
    }
    dispersion_plot(
        "Si", 
        axes[ind],
        dispersion_kwargs
    )
```

**Comment by ml-evs** [comment]
Thanks for bringing this to my attention @sajidurehman, I've updated the online example with the new argument name.

**Comment by sajidurehman** [comment]
Thank you for this new argument. Now working fine. 

I have one more query. Is it possibile to separatly save Si(s) and Si(p) data in .dat files?

**Comment by ml-evs** [comment]
Not easily (at least not in the same format as OptaDOS writes them). 

You can load the projectors into Python with [`matador.scrapers.optados2dict`](https://docs.matador.science/en/stable/matador.scrapers.html#matador.scrapers.optados2dict) and then save the projectors into files with numpy. The result of optados2dict should be a dictionary with keys "projectors", "projector_weights," kpoints" etc.

**Comment by sajidurehman** [comment]
Could you please help me in this regard. As know you i am not much fimilar with codes.  

Like as per my understanding 

from matador.scrapers import bands2dict, optados2dict, cell2dict
pdis_data, s = optados2dict("Si.pdis.dat")
bands_data, s = bands2dict("Si.bands")
cell_data, s = cell2dict("Si.cell")

after that i dont know what to do. Looking forward to your kind help. Thank you in advance

**Comment by ml-evs** [comment]
I'm not sure what you want to write in the file, but if you run that snipped you will see that `pdis_data` is a Python dictionary containing all the data about the projected dispersion, e.g.

```
{
    "projectors": [("Si", "s", None), ("Si", "p", None)],
    "projector_weights": <num_kpoints x num_bands x num_projectors array>,
    "kpoints": <num_kpoints x 3 array>
    "eigenvalues": <num_kpoints x num_bands array>
}
```

I'm afraid you're on your own from there.

**Comment by sajidurehman** [comment]
Thank you so much for the hint and direction.
