### ISSUE TITLE
Statement of need in documentation

### ISSUE THREAD

**Issue by srmnitc** [ml-evs/matador#122]
This is part of the review at openjournals/joss-reviews#2563

The JOSS checklist mentions that there should be statement of need in the documentation. However, I was unable to find this.

**Comment by ml-evs** [comment]
Hi @srmnitc,

I see the check you mention in the JOSS review checklist; whilst there is no explicit "Statement of Need" section in the documentation, I think the README provides an appropriate summary of the package and it's intended audience as it stands. Looking at a few accepted JOSS repos, I can't see any with an explicit section, which I think is what you're asking for?

I'll close this issue on that note, but please feel free to reopen it if you either think it is not clear in the current README, or if my interpretation of the guidelines is incorrect.

**Comment by srmnitc** [comment]
Yeah, I agree with you here @ml-evs . The core functionality section of the documentation is clear enough.
