### ISSUE TITLE
Electronic Band Structure Issue

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#127]
Hi Matthew,
                I am facing issue regarding bandgap energy by using matador. I am trying calculate electronic band structure of 2D GeN3 monolayer. I tried different potentials and also setting up set_efermi_zero: True and False. But everytime I am facing metallic behaviour. I tried in Materials Studio (MS) and got bandgap. I also tried to use same potentials from MS library in matador calculation but still getting metallic behaviour. I am confuse whats going wrong. Could you please help me in this regards. Thank you in advance.

**Comment by ml-evs** [comment]
Could you post your input files please?

**Comment by sajidurehman** [comment]
Please find the attachment
[GeN3.zip](https://github.com/ml-evs/matador/files/5305966/GeN3.zip)

**Comment by ml-evs** [comment]
Are you sure that .res file is correct? If you convert it to a cell, and compare it to the MS  studio cell, do they look the same? When I open that .res in VESTA, all the atoms appear to be overlapping...

**Comment by sajidurehman** [comment]
Yes, you are right! there was difference between between MS and .res file. But right now I used the MS .cell file (please see the attachment) in matador calculation but still getting metallic behaviour.

[res file.zip](https://github.com/ml-evs/matador/files/5306158/res.file.zip)

**Comment by ml-evs** [comment]
Can you post the log of the matador run please? It's not been written with 2D materials in mind, so there's a chance that it is standardizing the cell in some peculiar way. You should also check the matador generated cell files in the results folder, and check that they still make sense.

**Comment by sajidurehman** [comment]
Please find the log file.

[logs.zip](https://github.com/ml-evs/matador/files/5306383/logs.zip)

**Comment by sajidurehman** [comment]
One morething, I have tried before 2D GaN in matdor and its result almost same as MS calculation. So, in my opinion matador is working fine for 2D materials.

**Comment by ml-evs** [comment]
I can't see any problem with what run3 is doing here, the cell remains the same throughout and it looks reasonable in VESTA. 

From the bandstructure you sent, it looks like semi-metal. It also looks like the OptaDOS DOS is using a different Fermi level to the CASTEP run; this can be the case if OptaDOS computes a different Fermi level to CASTEP (e.g. if you do not use `set_efermi_zero: true`, or they are just computed differently numerically). You should compare your OptaDOS and CASTEP output files for this. It may also be the case that you need tighter electronic convergence parameters (e.g. `elec_energy_tol`) in order for the Fermi level to lie properly in that gap. I'm not sure what matstudio uses as defaults compared to CASTEP itself.

**Comment by sajidurehman** [comment]
Thank you for detailed reply. I have notice one morething: .cif and .res structure is slightly different (please see the fig). I used the cif3shx script for converting. Do you think this is Ok?
Do you think this cause problem in band structure calculation?

![cif-res](https://user-images.githubusercontent.com/33825577/94728951-73e1bf80-037a-11eb-98a6-118982cb62c8.png)

**Comment by ml-evs** [comment]
Do they look the same when you tile the cell more in vesta? Looks different atoms may be clipping outside the cell boundary in each so its hard to compare.

**Comment by sajidurehman** [comment]
Yes, I tried in different direction in VESTA.  Following are the details

cif      res
a         a     same
b         b     same
c         c      different
a*        a*   different
b*        b*   different
c*        c*   different

**Comment by ml-evs** [comment]
I meant more changing the boundary cutoffs, what happens if you look at 3x3x3 supercells of each variant? Do they look the same?

**Comment by sajidurehman** [comment]
No, looks different. Please find the attachment of .cif and .res files.
![cif-res (3x3x1)](https://user-images.githubusercontent.com/33825577/94744720-e3fc3f80-0392-11eb-994f-b53ddb00f391.png)
[cif+res.zip](https://github.com/ml-evs/matador/files/5308466/cif%2Bres.zip)

**Comment by ml-evs** [comment]
They look identical to me; the only difference is that some atoms are shifted from say -0.00001 to 0.00001, so VESTA is drawing them on different sides of the cell boundary. The "middle" of that 3x3x1 supercell, i.e. the original primitive cell is identical. 

Another way of seeing this is to increase the N-N bond length in VESTA, such that atoms outside of the boundary get included in the bonding, or choose the Boundary Mode "Search additional atoms recursively if either A1 or A2 is visible"  in the VESTA bond settings. With this setting, both files look identical, so I don't think there's any issue there either.

(be warned, this only works well for this structure as the N motifs are localised, if you have some extended structure this will crash VESTA...)

**Comment by sajidurehman** [comment]
Thank you so much for clarification.
