### ISSUE TITLE
Projected Band Structure Issue

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#135]
Hi Matthew,
                I am trying to run pojected band structure example of Si with matador 0.9.9. But I am facing following error. Could you please help me how to fix this error.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-1c5e46d1209d> in <module>
     12         "Si",
     13         axes[ind],
---> 14         dispersion_kwargs
     15     )
     16 

~/matador/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     82         except Exception as exc:
     83             if 'TclError' not in type(exc).__name__:
---> 84                 raise exc
     85 
     86             print_failure('Caught exception: {}'.format(type(exc).__name__))

~/matador/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     78             # now actually call the function
     79             set_style(style)
---> 80             result = function(*args, **kwargs)
     81 
     82         except Exception as exc:

~/matador/matador/plotting/spectral_plotting.py in dispersion_plot(seeds, ax_dispersion, options, bbox_extra_artists)
    435                 bbox_extra_artists,
    436                 eigs=eigs,
--> 437                 **options,
    438             )
    439             options["band_colour"] = "grey"

~/matador/matador/plotting/spectral_plotting.py in projected_bandstructure_plot(dispersion, ax, path, bbox_extra_artists, eigs, pdis_interpolation_factor, pdis_point_scale, projectors_to_plot, **options)
    963     projector_labels, dos_colours = _get_projector_info(
    964         projectors,
--> 965         colours_override=options["colour_cycle"] if options.get("colours") else None,
    966     )
    967 

KeyError: 'colour_cycle'

Best Wishes
Sajid

**Comment by ml-evs** [comment]
I'm afraid I can't replicate this, `colour_cycle` is always set explicitly in the code before this point so not sure what can be going wrong. I would suggest you install from PyPI (`pip install matador-db`) directly rather than installing from source, there's a chance you're using different versions of the code in different places.

**Comment by sajidurehman** [comment]
Sorry for inconvenience. As per your suggestion I uninstall existing version and then installed with pip install matador-db. Unfortunately, still i am facing same error.  I don't know what is going wrong.

**Comment by ml-evs** [comment]
Could you please post a zip of the folder you are running this in, and the command you are running? If you have created your own `.matadorrc` file it would be helpful to see that too.

**Comment by sajidurehman** [comment]
Please find the attachment.  No, I didnt created the .matadorrc file. Thank you for your help and time
[completed.zip](https://github.com/ml-evs/matador/files/5709239/completed.zip)

**Comment by ml-evs** [comment]
Ah, I see, I didn't appreciate that you were running the example notebook, I'd wrongly assumed you were using the dispersion script.

This "hack" hasn't been updated for the latest version of matador yet, if you just want to get it to run then you can add `"colour_cycle": [colours_override[ind]],` above `"colours": [colours_override[ind]],` in the function arguments.

**Comment by sajidurehman** [comment]
Oh Sorry for inconvenience. I didn't mention about jupyter notebook. Thank you for solution. But, i am getting same colours for both projected band structure.  Could you please let me know more how to change colours each projected band structure?

**Comment by ml-evs** [comment]
Make sure you're including the old "colours" argument too, so you end up with the cell

```python
fig, axes = plt.subplots(1, 2, figsize=(10, 5), sharey=True)
colours_override = ["firebrick", "darkorchid"]

for ind, proj in enumerate([[("Si", "s", None)], [("Si", "p", None)]]):
    dispersion_kwargs = {
        "projectors_to_plot": proj, 
        "plot_pdis": True, 
        "pdis_interpolation_factor": 10,
        "colour_cycle": [colours_override[ind]],
        "colours": [colours_override[ind]]
    }
    dispersion_plot(
        "Si", 
        axes[ind],
        dispersion_kwargs
    )
    
axes[1].set_ylabel(None)
plt.tight_layout()
```

which looks like this for me:

![image](https://user-images.githubusercontent.com/7916000/102495719-5ca79980-406e-11eb-995e-f30bc8f5c4cc.png)

**Comment by sajidurehman** [comment]
Thank you so much now got the required graphs. 
If you dont mind I have a one more query regarding PDOS the second example in same notebook. Following is the error.

KeyError                                  Traceback (most recent call last)
<ipython-input-5-b7163ef9118d> in <module>
      8         "plot_pdos": True
      9     }
---> 10     dos_plot("Si", axes[ind], dos_kwargs)
     11 axes[0].set_xlabel(None)
     12 plt.tight_layout()

~/.local/lib/python3.6/site-packages/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     82         except Exception as exc:
     83             if 'TclError' not in type(exc).__name__:
---> 84                 raise exc
     85 
     86             print_failure('Caught exception: {}'.format(type(exc).__name__))

~/.local/lib/python3.6/site-packages/matador/plotting/plotting.py in wrapped_plot_function(*args, **kwargs)
     78             # now actually call the function
     79             set_style(style)
---> 80             result = function(*args, **kwargs)
     81 
     82         except Exception as exc:

~/.local/lib/python3.6/site-packages/matador/plotting/spectral_plotting.py in dos_plot(seeds, ax_dos, options, bbox_extra_artists)
    746             if options.get("projectors_to_plot") is not None:
    747                 pdos = dict()
--> 748                 for projector in pdos_data["pdos"]["projectors"]:
    749                     if projector in options.get("projectors_to_plot"):
    750                         pdos[projector] = pdos_data["pdos"][projector]

KeyError: 'projectors'

**Comment by ml-evs** [comment]
That other example requires external data that I pulled in just to generate the plots, so you'll have to adapt it for the case you want to look at.

I'm going to close this issue now, but thanks for pointing this out, I've updated the example notebook with the extra required line.

**Comment by sajidurehman** [comment]
Sorry I just noticed that pdos example is not about Si after your suggestion. Thank you

**Comment by sajidurehman** [comment]
I want to pull request of scissor cut for electronic band structure and DOS. Is it possible to add this feature in matador?

**Comment by ml-evs** [comment]
Sure, did you want to raise a separate issue for that?

**Comment by sajidurehman** [comment]
If it is necessary I will raise otherwise requesting here it is fine for me.

**Comment by ml-evs** [comment]
It would be good to raise another issue describing exactly what you want, and what you're trying to do, perhaps someone else might be able to implement it before me

**Comment by sajidurehman** [comment]
Ok thank you for right direction.
