### ISSUE TITLE
HSE03 Calculation Issue

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#141]
Hi Matthew,
                 I am trying to run the HSE03 calculation with matador. There is some error in dealing with .odi file.  Please see the attached files. Could you please guide me how to fix this issue.
[matador@HSE03.zip](https://github.com/ml-evs/matador/files/5729956/matador%40HSE03.zip)
 
Looking forward to your kind help.

Best Wishes
Sajid

**Comment by ml-evs** [comment]
From memory, CASTEP does not produce the `.dome_bin` file when running with hybrid functionals. OptaDOS needs this file for many of its tasks. I'm afraid this is something you should raise with the OptaDOS or CASTEP developers.

**Comment by sajidurehman** [comment]
Thank you for clarifying the issue.
