### ISSUE TITLE
Error: Executable `castep` failed testing

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#44]
Hi Matthew,
               I have successfully installed the CASTEP 19.11 (academic license version) and got the executable castep.mpi file. Then, successfully run the simple calculation. Also, added in ubuntu (18.04) PATH.

Moreover, I have successfully installed the matador. When I tried to run the following example for projected band structure and DOS. 

https://docs.matador.science/en/latest/tutorials/run3_spectral.html#example-2-4-using-optados-for-post-processing-projected-dos-and-bandstructur

I got the following error. Please help me how to fix this error. 
```
Loading perhaps unsuitable defaults instead.
Loading settings from /home/max/.local/lib/python3.6/site-packages/matador/config/matadorrc.yml
2020-05-20 16:49:11,229 - run3 |     INFO: 
                           _____
          _ __ _   _ _ __ |___ /
         | '__| | | | '_ \  |_ \
         | |  | |_| | | | |___) |
         |_|   \__,_|_| |_|____/

        
2020-05-20 16:49:11,229 - run3 |     INFO: matador version: 0.8b1-849-gc48fae8-ml-evs-fix-tcl-error
2020-05-20 16:49:11,229 - run3 |     INFO: Host info: Linux-qmobile-4.15.0-65-generic-#74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019-x86_64.
2020-05-20 16:49:11,230 - run3 |     INFO: Run started for seed LiCoO2-CollCode29225
2020-05-20 16:49:11,232 - run3 |     INFO: Testing executable "castep".
2020-05-20 16:49:11,239 - run3 |     INFO: Using default MPI library.
2020-05-20 16:49:11,239 - run3 |     INFO: Detected default MPI.
2020-05-20 16:49:11,239 - run3 |     INFO: Running ['mpirun', '-n', '2', 'castep', '--version']
2020-05-20 16:49:11,399 - run3 | CRITICAL: Executable `castep` failed testing: does it support --version flag?
2020-05-20 16:49:11,399 - run3 | CRITICAL: stdout: --------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       qmobile
Executable: castep
--------------------------------------------------------------------------
2 total processes failed to start

2020-05-20 16:49:11,399 - run3 | CRITICAL: sterr: 
2020-05-20 16:49:11,399 - run3 |    ERROR: Process raised <class 'matador.utils.errors.CriticalError'> with message Executable `castep` failed testing: does it support --version flag?.
Fatal error(s) reported:
Executable `castep` failed testing: does it support --version flag?
Some jobs failed, exiting...
```

Best regards
Sajid

**Comment by ml-evs** [comment]
Hi Sajid, you just need to change the name of the CASTEP executable.

The matador default is simply `castep` but a fresh install of CASTEP will give you the executable `castep.mpi`, as you mentioned.

You have a few options:
- specify `--executable castep.mpi` when you run run3, 
- or symlink `castep.mpi` to `castep` on your PATH,
- or create a .matadorrc file that contains the setting below:

```
run3:
    castep_executable: castep.mpi
```

**Comment by sajidurehman** [comment]
Hi Matthew,
              Thank you for prompt reply and thank you for solution. But after successful completion of calculation and executing command: dispersion LiCoO2-CollCode29225 

I got blank figure there is nothing inside the figure. Please let me know about this issue. Thank you

**Comment by ml-evs** [comment]
Could you post the log of the calculation? If it completed successfully you should run that command from inside the `completed` folder.

**Comment by ml-evs** [comment]
I actually fixed it today so that `dispersion` will notify you if the files are missing, if you update to 0.9.1 with pip.

**Comment by sajidurehman** [comment]
Sorry I executed the command from outside. Now its working fine. Thank you for correcting me.
Do you mean by : pip install matador ?

**Comment by ml-evs** [comment]
The package on PyPI is unfortunately called matador-db, but you can now do `pip install matador-db` instead of the git steps. If you already have it installed locally then you can just pull the master branch and reinstall.

**Comment by sajidurehman** [comment]
Thank you got it. By the way I tried projected band structure and DOS example but i got simple band strucrture and total DOS why ? I used your .cell and .param files.

**Comment by ml-evs** [comment]
That will depend on how you have installed OptaDOS alongside CASTEP.

**Comment by sajidurehman** [comment]
I separatly installed OptaDOS. is it correct way or not ?

**Comment by ml-evs** [comment]
That's fine, but you will need to make sure the correct optados executable is being used by run3 as well, it should be clear in the logs if that isn't the case.

**Comment by ml-evs** [comment]
You also need to make sure you have an optados input file, as per the instructions

**Comment by sajidurehman** [comment]
Yes you are right about optados. seen following error in logs 
stderr: nice: ‘optados’: No such file or directory

but, I have correctly added in ubuntu PATH. When typed optados.x shows me following message

OptaDOS ver. 1.2

  Andrew J. Morris, R. J. Nicholls, C. J. Pickard and J. R. Yates (c) 2010-2015
  Usage: optados <seedname>

So, its look fine to me. Any suggestion regarding this issue?

**Comment by ml-evs** [comment]
That's the same problem again, it can't find the binary "optados" because you have it saved as "optados.x", so you need to rename it or do the same steps as above for castep. The relevant setting is

```
run3:
    optados_executable: optados.x
```

**Comment by sajidurehman** [comment]
Thank you now got the right figure. 

I have few queries. could you please help me in this regards.
1) How to set band paths for 2D materials like K-M-G-K? 
2) do we need to make .res file by ourself for each material/compound?

**Comment by ml-evs** [comment]
1. Not possible with matador I'm afraid, you'll have to set the paths manually in your cell file.
2. matador comes with a lot of scripts to convert between common file types, so that's the easiest way. e.g. `cif3shx`, `cell3shx`, etc will write res files (shx stands for SHELX, the original res format).

**Comment by sajidurehman** [comment]
Thank you, simple and efficient solution.

I want to learn more about its proper usage. So, please help me in following queries.
1) how to set the energy range in Band structure and DOS like from -5 to 5?
2) how to use the different colors for orbitals s, p, d?
3) how to export the figure with 600dpi?

Thank you in advance. looking forward to hear tou again.
