### ISSUE TITLE
Calculate gaps between arbitrary projected bands: application to heterostructures

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#48]
Hi Matthew,
                 Thank you for adding feature for each projector band structure. In case of heterostructure when executing following command 
dispersion GeC@GaN --bs -g -p Ga,N 

It shows me the direct and indirect band gap of heterostructure but i am interested in individual band gaps. Because we need to investigate the effect on band gaps (increased or decreased) of each compound (like GaN or GeC) in heterostructure.  Is it possible to calculate that kind of band gaps.

**Comment by ml-evs** [comment]
I don't think I'll be implementing band gaps between different projectors as it is not generally useful (and it would be quite tricky to define). Have you considered measuring the appropriate gaps from the PDOS instead of the bandstructure? If you know some python, you could use the underlying models in matador (https://github.com/ml-evs/matador/blob/master/matador/orm/spectral/dos.py#L26) to automate this process to calculate the gaps you want.

**Comment by sajidurehman** [comment]
Have you considered measuring the appropriate gaps from the PDOS instead of the bandstructure?
No, because we cannot calculate DOS of combined projectors like GaN in GeC@GaN heterostructure. Although we have each projector PDOS but calculating band gap from that PDOS is not useful. I hope you got my point. It will be useful if we could be able to calculate PDOS of GaN in heterostructure.

Sorry, i am not much familar with coding. So, its hard for me.

**Comment by sajidurehman** [comment]
Hi @ml-evs Please find the files in following link. Thank you so much for this great help. 

https://drive.google.com/file/d/1lG0Z645pls0PXlgzsNaeXrStcJ1a4b_W/view?usp=sharing

**Comment by ml-evs** [comment]
Here's a script/notebook that takes your existing data and adds the projectors together [GeC@GaN_pdos.zip](https://github.com/ml-evs/matador/files/4724341/GeC%40GaN_pdos.zip). I'm afraid I can't spend any more time on this, good luck!

**Comment by ml-evs** [comment]
(Note you'll need to be on the master branch, or version 0.9.3 when its released).

**Comment by sajidurehman** [comment]
Hi @ml-evs thank you so much for this script and for your precious time  and effort. I will always be thankful to you.
