### ISSUE TITLE
--pdos_hide_tot flag for dispersion is misleading

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#56]
Hi Matthew,
                I am trying to hide the total DOS plot in PDOS. I am executing following command 
                dispersion GaN --dos --pdos_hide_tot
Is this right way? But getting same PDOS before and after --pdos_hide_tot.

**Comment by ml-evs** [comment]
Hi @sajidurehman, I'm afraid this is an old flag that now has a misleading name (and help string). 

`--pdos_hide_tot` can be used in conjunction with `--unstacked_pdos` to hide the **sum** of the PDOS's from the plot, but not the total DOS itself. Note that the difference between the sum of the PDOS and the total DOS indicates how "atomic-like" the underlying states are.

There is currently no way to hide the **total DOS** from a PDOS plot as it provides useful information. I'll rename the flag to `--pdos_hide_sum` at the next release.

**Comment by sajidurehman** [comment]
Thank you for detailed reply and explanation.  Thank you great support and for more and more exciting features.
