### ISSUE TITLE
get_uniq_cursor does not print output for all input

### ISSUE THREAD

**Issue by JordD04** [ml-evs/matador#78]
When passing cursors to get_uniq_cursor, the script runs, and performs a number of iterations equal to the number of res files input, but it does not print output for all cursors, e.g.:
0: {1, 18, 6, 7}
2: {13}
3: {17, 14}
4: {15}
5: set()
8: {9, 10, 19, 20}
The number of missing res files always seems to be greater than the number of files which are intentionally skipped.
I've tried to trace the problem back but I've gotten stuck.
It seems that things are missing from sim_mat in similarity.py, so it must be before then.
All cursors seem to be present and working by line 201 in fingerprint.py (cursor[ind][self.default_key].calculate()) but I don't know where to follow the code to because the remaining code for that class is under an else: statement.

Tar included with test files.

[uniq_cursor_ticket.tar.gz](https://github.com/ml-evs/matador/files/4869973/uniq_cursor_ticket.tar.gz)

**Comment by ml-evs** [comment]
Hi @JordD04, could you also provide a minimal python script that replicates this from the latest matador release?

**Comment by ml-evs** [comment]
This seems to work fine for me:

```python
from matador.scrapers import res2dict
from matador.fingerprints import get_uniq_cursor
from matador import __version__

cursor, failures = res2dict("*.res")
uniq_inds, dupe_dict, fingerprints, sim_mat = get_uniq_cursor(cursor)
print(f"matador version: {__version__}")
print(uniq_inds)
print(dupe_dict)
```

Output:
```
Successfully scraped 22 out of 22 files.
Calculating fingerprints...
Assessing similarities...
Skipping 3 structures out of 22 as no comparisons are required
Running 19 jobs on at most 8 processes, set by core count.
Applying hierarchy of structures with order: ['ICSD', 'DOI', 'OQMD', 'MP', 'PF', 'SWAPS', 'AIRSS', 'GA']
Done!
matador version 0.9.5
[0, 2, 3, 4, 5, 8, 11, 16, 21]
{0: {1, 18, 6, 7}, 2: {13}, 3: {17, 14}, 4: {15}, 5: set(), 8: {9, 10, 19, 20}, 11: {12}, 16: set(), 21: set()}
```

**Comment by JordD04** [comment]
Hey, sorry I didn't see this sooner. I wasn't expecting you to get round to it so quickly.
Thanks for looking into this.
Looks like I misunderstood how it was working, I thought it was supposed to print one key for every res.
I thought I had checked this but I must have made a mistake.
 
Thanks again.
